2024-06-24 18:08:06,499 p=3444395 u=upszot n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was 127.0.0.1

2024-06-24 18:08:06,598 p=3444395 u=upszot n=ansible | PLAY [all] **********************************************************************************************************************************************************************************************************************************
2024-06-24 18:08:06,609 p=3444395 u=upszot n=ansible | TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
2024-06-24 18:08:07,746 p=3444395 u=upszot n=ansible | ok: [localhost]
2024-06-24 18:08:07,775 p=3444395 u=upszot n=ansible | TASK [include_role : 2do_parcial] ***********************************************************************************************************************************************************************************************************
2024-06-24 18:08:07,805 p=3444395 u=upszot n=ansible | TASK [2do_parcial : debug] ******************************************************************************************************************************************************************************************************************
2024-06-24 18:08:07,817 p=3444395 u=upszot n=ansible | ok: [localhost] => {
    "msg": "Tareas del 2do Parcial"
}
2024-06-24 18:08:07,836 p=3444395 u=upszot n=ansible | TASK [Otra tarea] ***************************************************************************************************************************************************************************************************************************
2024-06-24 18:08:07,851 p=3444395 u=upszot n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-06-24 18:08:07,885 p=3444395 u=upszot n=ansible | PLAY RECAP **********************************************************************************************************************************************************************************************************************************
2024-06-24 18:08:07,885 p=3444395 u=upszot n=ansible | localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-24 23:58:37,757 p=3653 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-24 23:58:38,839 p=3653 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-24 23:58:38,917 p=3653 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-24 23:58:39,215 p=3653 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-24 23:58:42,647 p=3653 u=vagrant n=ansible | ok: [localhost]
2024-06-24 23:58:42,711 p=3653 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-24 23:58:42,757 p=3653 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "Directorios"
      shell: sudo mkdir -p /tmp/2do_parcial/{alumno,equipo}
      ^ here

2024-06-24 23:58:42,760 p=3653 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-24 23:58:42,761 p=3653 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-24 23:58:42,762 p=3653 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:01:04,081 p=3874 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:01:04,581 p=3874 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:01:04,605 p=3874 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:01:04,787 p=3874 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:01:07,945 p=3874 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:01:07,973 p=3874 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:01:08,016 p=3874 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 9, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  shell: sudo mkdir -p /tmp/2do_parcial/{alumno,equipo}
      args:
          ^ here

2024-06-25 00:01:08,021 p=3874 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:01:08,022 p=3874 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:01:08,022 p=3874 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:01:59,594 p=3975 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:01:59,979 p=3975 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:02:00,006 p=3975 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:02:00,163 p=3975 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:02:02,253 p=3975 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:02:02,283 p=3975 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:02:02,315 p=3975 u=vagrant n=ansible | ERROR! conflicting action statements: shell, creates

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "Directorios"
  ^ here

2024-06-25 00:02:02,317 p=3975 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:02:02,318 p=3975 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:02:02,319 p=3975 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:03:44,670 p=4086 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:03:45,083 p=4086 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:03:45,101 p=4086 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:03:45,729 p=4086 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:03:48,123 p=4086 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:03:48,163 p=4086 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:03:48,215 p=4086 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 8, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "Directorios"
    shell: sudo mkdir -p /tmp/2do_parcial/{alumno,equipo}
    ^ here

2024-06-25 00:03:48,220 p=4086 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:03:48,221 p=4086 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:03:48,222 p=4086 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:05:08,539 p=4187 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:05:08,834 p=4187 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:05:08,869 p=4187 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:05:09,459 p=4187 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:05:12,030 p=4187 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:05:12,057 p=4187 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:05:12,099 p=4187 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 14, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "Obtener IP"
    command: curl -s ifconfig.me
    ^ here

2024-06-25 00:05:12,102 p=4187 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:05:12,103 p=4187 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:05:12,104 p=4187 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:06:02,435 p=4289 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:06:02,774 p=4289 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:06:02,795 p=4289 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:06:03,383 p=4289 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:06:05,798 p=4289 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:06:05,841 p=4289 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:06:05,885 p=4289 u=vagrant n=ansible | ERROR! conflicting action statements: shell, creates

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "Directorios"
  ^ here

2024-06-25 00:06:05,889 p=4289 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:06:05,890 p=4289 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:06:05,890 p=4289 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:08:47,881 p=4392 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:08:48,239 p=4392 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:08:48,259 p=4392 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:08:48,387 p=4392 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:08:51,579 p=4392 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:08:51,614 p=4392 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:08:51,654 p=4392 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 7, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


tasks:
^ here

2024-06-25 00:08:51,660 p=4392 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:08:51,662 p=4392 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:08:51,663 p=4392 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:10:14,175 p=4493 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:10:14,529 p=4493 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:10:14,544 p=4493 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:10:14,685 p=4493 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:10:17,050 p=4493 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:10:17,101 p=4493 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:10:17,156 p=4493 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: "Directorios"
  ^ here

2024-06-25 00:10:17,160 p=4493 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:10:17,163 p=4493 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:10:17,163 p=4493 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:10:47,345 p=4595 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was
127.0.0.1

2024-06-25 00:10:47,865 p=4595 u=vagrant n=ansible | PLAY [all] *******************************************************************************************
2024-06-25 00:10:47,922 p=4595 u=vagrant n=ansible | TASK [Gathering Facts] *******************************************************************************
2024-06-25 00:10:48,221 p=4595 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey).", "unreachable": true}
2024-06-25 00:10:50,609 p=4595 u=vagrant n=ansible | ok: [localhost]
2024-06-25 00:10:50,637 p=4595 u=vagrant n=ansible | TASK [include_role : 2do_parcial] ********************************************************************
2024-06-25 00:10:50,671 p=4595 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/vagrant/UTN-FRA_SO_Examenes/202406/ansible/roles/2do_parcial/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: "Obtener IP"
  ^ here

2024-06-25 00:10:50,672 p=4595 u=vagrant n=ansible | PLAY RECAP *******************************************************************************************
2024-06-25 00:10:50,673 p=4595 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-06-25 00:10:50,673 p=4595 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
